export { default as LearnC } from './LearnC';
export { default as Users } from './Users';
export { default as UploadLessonData } from './UploadLessonData';
export { default as Calendar } from './Calendar';
export { default as UploadVideo } from './UploadVideo';
export { default as UploadTests } from './UploadTests';
export { default as LessonForm } from './LessonForm';
export { default as Tests } from './Tests';
export { default as Lessons } from './Lessons';